animation:
  animation_directory: "/home/ancey/Lac_Clusaz/Figures/Vid\xE9os"
  label_step: 500
  making_html: false
  n_out: 120
  variable: depth
computation:
  boundary: extrap
  cell_size: 2
  cfl_max: 1
  cfl_target: 0.5
  dry_limit: 0.0001
  force_stop: false
  initial_mass: true
  limiter: vanleer
  mass_frac_stop: 0.01
  mass_threshold_velocity: 0.01
  max_iter: 100000
  nb_simul: 120
  output_directory: _output
  refinement: 1
  t_max: 120
  topo_dir: /home/ancey/Lac_Clusaz/Topo
  track_mass: true
dem_extent:
  cell_size: 2.0
  nbx: 1500
  nby: 1000
  nodata_value: -9999
  xmax: 967998.20001221
  xmin: 965000.20001221
  ymax: 6536998.08996582
  ymin: 6535000.08996582
file_names:
  initiation_file: init.xyz
  topo_source: real_world
  topofile: topography.asc
  type_dem: 3
  type_init: 1
  topo_directory: /home/ancey/Lac_Clusaz/Topo
gauges:
  gauge_recording: true
  gauges:
  - - 1
    - 965780.0
    - 6536190.0
output:
  Language: French
  delta_t: 1
  output_directory: _output300
  output_format: binary32
  verbosity: 0
refinement:
  delta_t: null
  fine_dict: None
  finer_dem: None
  topo_refinement: false
release:
  correction_elevation: true
  correction_slope: true
  d0: 1.75
  gradient_hypso: 0.03
  nu: 0.2
  period_return: 300
  theta_cr: 30
  z_ref: 1300
rheology:
  C: 0
  beta: 0.0
  model: Voellmy
  mu: 0.225
  rho: 300
  u_cr: 0
  xi: 1200
