# Makefile for AVAC 4: version = 4.3
# Makefile for Clawpack code in this directory.
# This version only sets the local files and frequently changed
# options, and then includes the standard makefile pointed to by CLAWMAKE.
# Last update: 12 April 2026
CLAWMAKE = $(CLAW)/clawutil/src/Makefile.common

# See the above file for details and a list of make options, or type
#   make .help
# at the unix prompt.


# Adjust these variables if desired:
# ----------------------------------

CLAW_PKG = geoclaw             # Clawpack package to use
EXE = xgeoclaw                 # Executable to create
SETRUN_FILE = setrun.py        # File containing function to make data
OUTDIR = _output               # Directory for output
SETPLOT_FILE = setplot.py      # File containing function to set plots
PLOTDIR = _plots               # Directory for plots

# Environment variable FC should be set to fortran compiler, e.g. gfortran

# Compiler flags can be specified here or set as an environment variable
FFLAGS ?= -O2 -fopenmp
OMP_NUM_THREADS = 8


# ---------------------------------
# package sources for this program:
# ---------------------------------

GEOLIB = $(CLAW)/geoclaw/src/2d/shallow
include $(GEOLIB)/Makefile.geoclaw

# ---------------------------------------
# package sources specifically to exclude
# (i.e. if a custom replacement source 
#  under a different name is provided)
# ---------------------------------------

EXCLUDE_MODULES = \

EXCLUDE_SOURCES = \
  $(GEOLIB)/b4step2.f90 \

# ----------------------------------------
# List of custom sources for this program:
# ----------------------------------------

# Topography type: set REAL_WORLD_TOPO=1 (real) or 0 (synthetic)
# This variable is written automatically by the notebook into config.mk
REAL_WORLD_TOPO ?= 1
-include config.mk

ifeq ($(REAL_WORLD_TOPO),1)
MODULES = \
  ./rheology_module.f90 \
  ./qinit_module.f90
else
MODULES = \
  ./rheology_module.f90
endif

SOURCES = \
  ./src2.f90 \
  ./setprob.f90 \
  ./b4step2.f90 \
  ./rpn2_geoclaw.f \
  $(CLAW)/riemann/src/rpt2_geoclaw.f \
  $(CLAW)/riemann/src/geoclaw_riemann_utils.f \

ifeq ($(REAL_WORLD_TOPO),0)
SOURCES += ./qinit.f90
endif
#-------------------------------------------------------------------
# Include Makefile containing standard definitions and make options:
include $(CLAWMAKE)

# Construct the topography data
.PHONY: topo all
animation:
	python make_fgout_animation.py
#
all: 
	$(MAKE) topo
	$(MAKE) .plots
#	$(MAKE) .htmls

